pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // 🔥 必须有下面这一行，它是找到 adb 库的关键！
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "ADB"
include ':app'
